version: '3'
services:
  mysql-rust-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql-db-rust-volume:/var/lib/mysql
      - ./the_fun_db.sql:/docker-entrypoint-initdb.d/init.sql

# Names our volume
volumes:
  mysql-db-rust-volume: